export const ADD_FAVORITE_DOGS = "ADD_FAVORITE_DOGS";
export const LOAD_FAVORITE_DOGS = "LOAD_FAVORITE_DOGS";
export const GET_FAVORITE_DOGS = "GET_FAVORITE_DOGS";
export const DELETE_FAVORITE_DOGS = "DELETE_FAVORITE_DOGS";






export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";



